services:
  auth_backend:
    container_name: auth_ms
    build: .
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    ports:
      - 8001:8000
    depends_on:
      - auth_db
    links:
      - auth_db
    networks:
      - auth
      - shared-network

  auth_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - auth
      - shared-network

networks:
  auth:
    name: auth
  shared-network:
    external: true
