version: '3.9'
services:
  checkout_backend:
    build: .
    ports:
      - 8004:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - checkout_db
    links:
      - checkout_db
    networks:
      - checkout
      - shared-network

  checkout_queue:
    build: .
    command: 'php artisan queue:work'
    depends_on:
      - checkout_db
    links:
      - checkout_db
    networks:
      - checkout

  checkout_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - checkout
      - shared-network

networks:
  shared-network:
    external: true
  checkout:

