services:
  customer_backend:
    build: .
    ports:
      - 8003:8000
    volumes:
      - .:/app
    command: 'php artisan serve --host=0.0.0.0'
    depends_on:
      - customer_db
    links:
      - customer_db
    networks:
      - customer
      - shared-network

  customer_queue:
    build: .
    command: 'php artisan queue:work'
    environment:
      CACHE_DRIVER: file
    depends_on:
      - customer_db
    links:
      - customer_db
    networks:
      - customer

  customer_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: customer
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - customer
      - shared-network

  redis:
    image: redis
    ports:
      - 63799:6379
    networks:
      - customer

networks:
  shared-network:
    external: true
  customer:

